### ISSUE TITLE
Landing page should show all waterpoints of Iringa region

### ISSUE THREAD

**Issue by markiliffe** [taarifa/TaarifaWaterpoints#147]
On the 'home page' the map shows a variety of water markers "http://iringa.herokuapp.com/#/?max_results=100&reports_only=0". This focuses initially on Arusha, but as this is for Iringa, should show Iringa first. Also, only showing 1000 points is poor usability, really the map should show all markers for the region selected. This will be clunky, but correct. Currently showing only a small subset is misleading though more usable.

**Comment by kynan** [comment]
I think this is no longer relevant. The question does still remain whether showing the "random" first 100 waterpoints is a good strategy or not, but that's for another issue.
