### ISSUE TITLE
python manage.py runserver -r -d error

### ISSUE THREAD

**Issue by mtuchi** [taarifa/TaarifaWaterpoints#158]
```
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    from taarifa_api import add_document, delete_documents, get_schema
  File "/home/imma/.virtualenvs/TaarifaAPI/src/taarifaapi/taarifa_api/__init__.py", line 1, in <module>
    from taarifa_api import api, main, get_schema  # noqa
  File "/home/imma/.virtualenvs/TaarifaAPI/src/taarifaapi/taarifa_api/taarifa_api.py", line 59, in <module>
    api = Eve(API_NAME, validator=KeySchemaValidator, settings=settingsfile)
  File "/home/imma/.virtualenvs/TaarifaAPI/local/lib/python2.7/site-packages/eve/flaskapp.py", line 136, in __init__
    self.data = data(self)
  File "/home/imma/.virtualenvs/TaarifaAPI/local/lib/python2.7/site-packages/eve/io/base.py", line 100, in __init__
    self.init_app(self.app)
  File "/home/imma/.virtualenvs/TaarifaAPI/local/lib/python2.7/site-packages/eve/io/mongo/mongo.py", line 73, in init_app
    raise ConnectionException(e)
eve.io.base.ConnectionException: Error initializing the driver. Make sure the database serveris running. Driver exception: ConnectionFailure('[Errno 111] Connection refused',)
```

**Comment by fayazv** [comment]
Facing somehow similar issue on **mac**.


```
eve.io.base.ConnectionException: Error initializing the driver. 
Make sure the database serveris running. 
Driver exception: ConfigurationError('Unknown option auto_start_request',)
```

- mongod is running
- mongo TaarifaAPI is running and connecting, but throws a warning:

```
WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
```
To solve the above warning, I found a solution in [SO](http://stackoverflow.com/questions/16621763/mongod-mac-os-x-rlimits-warning). I'm not sure if it's safe to run 
```
launchctl limit maxfiles 2048 2048
```
- grunt serve --watch running

**Comment by kynan** [comment]
I don't have any experience running mongo on a Mac. Maybe @dgorissen can weigh in?

From the error message I suspect it is some incompatibility of your versions of Eve and pymongo. Can you post the output of `pip freeze` in your virtualenv?

According to the [pymongo 3.0 release notes](http://api.mongodb.org/python/current/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient), the `auto_start_request` option has been removed.

**Comment by fayazv** [comment]
**Fixed:** Downgraded pymongo from 3.0 to 2.8

For future reference, we should support pymongo 3.0+ (look for a way around `auto_start_request`)

**Comment by yathit** [comment]
@fayazv +1 thanks.

**Comment by kynan** [comment]
This option is actually set by [Flask-PyMongo](https://github.com/dcrosta/flask-pymongo/blob/master/flask_pymongo/__init__.py#L191-L209), which has not been updated for 3.0 compatibility, see dcrosta/flask-pymongo#59

We're blocked until this is fixed and Eve upgrades its dependency. Since this is a separate issue I'll close this one.
