### ISSUE TITLE
Insertion failure: service_code is not unique

### ISSUE THREAD

**Issue by fayazv** [taarifa/TaarifaWaterpoints#184]
When running the following scripts:
```
python manage.py create_facility
python manage.py create_service
```

throws the following error:
```
Failed with status 400
{'_error': {'code': 400,
            'message': 'Insertion failure: 1 document(s) contain(s) error(s)'},
 '_issues': {'facility_code': "value 'wpf001' is not unique"},
 '_status': 'ERR'}
```

**Comment by kynan** [comment]
Have you been running those multiple times without clearing your database?

**Comment by fayazv** [comment]
It worked after clearing the database

**Comment by kynan** [comment]
OK. I suppose we should either add a check or at least document this.

**Comment by fayazv** [comment]
A check would do. Since, what I had to do was:
```
use [database];
db.dropDatabase();
```
then run the two scripts.

**Comment by kynan** [comment]
Sure, but simply dropping the database is not a good idea since the user might have data in there already.

**Comment by fayazv** [comment]
In that case, this works too:
```
db.collection.remove(...)
```
OR
```
use [database];
db.collectionName.drop();
```

**Comment by kynan** [comment]
Yes, that'd be better. But the question is: do we want to make the manage task do nothing in case the collections already exist rather than drop and re-create them? That'd be my preference. @dgorissen?

**Comment by dgorissen** [comment]
if they already exist the safest thing is to do nothing and print a warning. Could do add a --drop or something if you want

**Comment by kynan** [comment]
Yep, that sounds like a reasonable compromise.
