### ISSUE TITLE
Unable to submit new report wptcode vs wpt_code

### ISSUE THREAD

**Issue by ricktetstall** [taarifa/TaarifaWaterpoints#186]
File: `taarifa_waterpoints/schemas.py`

         "relation": {"resource": "waterpoints",
                      "field": "wpt_code"}},

Is "field": `wpt_code` correct here? Or should it be `wptcode`?

I think my (possibly old) copy of the Taarifa db has field: `wptcode` as attributes on all items which prevents me from submitting new reports as I get the following error back from the server:

    waterpoint_id: "value '02032001082WP05' must exist in resource 'waterpoints', field 'wpt_code'.

Though altogether possible I'm barking up the wrong tree here...

**Comment by kynan** [comment]
Good catch, that should be `wptcode`. To help us reproduce the error you were seeing, how did you submit the report?

**Comment by ricktetstall** [comment]
I was using the http://...requests/new?... page to try to submit reports.
I've now dropped the only row in the services table in the db and recreated
the service using manage.py once is updated schemas.py and it all works

**Comment by kynan** [comment]
Great, thanks for investigating. I'll push a fix.
